### ISSUE TITLE
Trafo for DiscreteParams

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/ParamHelpers#10]
Jakob suggested to add that feature.

I currently did not see the need for that as one could simply set the DESIRED / TRAFOED values as the values of the param. 

But maybe there are cases where this is still helpful? 
Also: If it causes no problems, why not allow it, for consistency?

Thing is, I remember there was a complicating issue.
But if so, this must be documented in code. And the user must be informed WHY he does not need trafos for discretes. 

I will check this again.

**Comment by berndbischl** [comment]
@jakob-r 
Do you have any use case for this in mind?
Otherwise I would close this.

**Comment by jakob-r** [comment]
When I come up with a use case I will reopen.
