### ISSUE TITLE
Use deparse instead of capture.output for requirements

### ISSUE THREAD

**Issue by jakob-r** [berndbischl/ParamHelpers#103]
deparse might be faster and less prone to errors than capture.output

old `line = paste(line, collapse(capture.output(p$requires), sep=""), sep = " | ")`
suggest `line = paste(line, deparse(p$requires), sep = " | ")`

**Comment by jakob-r** [comment]
Taken care of #106

**Comment by berndbischl** [comment]
please dont close before the PR is merged, thats the convention
