### ISSUE TITLE
make*VectorLearnerParam converts lower to length of default

### ISSUE THREAD

**Issue by jakob-r** [berndbischl/ParamHelpers#145]
This is a bit ugly and results in confusing warnings for the user:

``` r
par = makeIntegerVectorLearnerParam(id = "test", default = c(10,10), lower = 0)
isFeasible(par, c(10,10,10))
# Error in x >= par$lower : 
#   (converted from warning) longer object length is not a multiple of shorter object length
```

This mainly happens in _mlr_ when you call `setHyperParams`

The problem is that internally the value for `lower` get convertet to `lower = c(0,0)`. 

My proposal: 
- If the lower value is atomic we keep it like that and it has the meaning that all values of the vector have to have in this boundary
- If the lower value is given as a vector we freeze the length and give an error when the user tries to change the values to another length

If you are okay with my proposals i will make a PR

**Comment by berndbischl** [comment]
1) your example now passes without error, and I have added a unit test at the end of test_isFeasible.

2) I have also added these checks and made PH here a bit conservative to not allow weird mixings of settings:

```
makeLearnerParam = function(p, when) {
  assertChoice(when, c("train", "predict", "both"))
  p$when = when
  if (isNumeric(p, include.int = TRUE) && isScalarNA(p$len)) {
    if (!is.expression(p$lower) && length(p$lower) != 1L)
      stopf("For learner vector param '%s' with unspecified length (NA), bound 'lower' can only be a scalar, but has length:", p$id, length(p$lower))
    if (!is.expression(p$lupper) && length(p$upper) != 1L)
      stopf("For learner vector param '%s' with unspecified length (NA), bound 'upper' can only be a scalar, but has length:", p$id, length(p$upper))
  }
  class(p) = c("LearnerParam", "Param")
  return(p)
}

```

3) can you please spend a few minutes to maybe add more unit tests, then close?

or tell me any further thoughts NOW pls

**Comment by jakob-r** [comment]
2. Gets already cought by
```r
if (isNumericTypeString(type, include.int = TRUE)) {
#  ...
    if (!is.expression(len) && !is.expression(lower)) {
      if (length(lower) %nin% c(1L, len))
        stopf("For param '%s' length 'lower' must be either 1 or length of param, not: %i", id, length(lower))
    }
    if (!is.expression(len) && !is.expression(upper)) {
      if (length(upper) %nin% c(1L, len))
        stopf("For param '%s' length 'upper' must be either 1 or length of param, not: %i", id, length(upper))
    }
  }
```
in [aParam.R](https://github.com/berndbischl/ParamHelpers/blob/2c3d75723b003410fcfc89396ccd6c7d6f21c01d/R/aParam.R#L108-L115)

**Comment by berndbischl** [comment]
done here thx
