### ISSUE TITLE
dict should not be in signature of functions that take a parset?

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/ParamHelpers#175]
or maybe it should? at least we need to look at whether we need that

ok, i might be wrong here. maybe somebody can add a comment

**Comment by jakob-r** [comment]
In addition to what I said in #174... One the one hand: If we put the dictionary to the ParSet then we could just directly evaluate the ParSet on the given dictionary... on the other hand it could maybe save us some additional arguments in the function calls but that only is not a good reason.

**Comment by berndbischl** [comment]
well, i would close this and going to call me suggestion wrong. 

the keys should be in the parset, the dict is passed on eval in the functions?

if you agree pls close

**Comment by jakob-r** [comment]
agree, I will make a PR
