### ISSUE TITLE
Add option to configure the output length of the tuning info

### ISSUE THREAD

**Issue by pat-s** [berndbischl/ParamHelpers#204]
For example, `Tune-x] 9: C=147; sigma=0.0615; fw.perc=0.463; fw.basal.methods=FSelector_re...` should not be truncated. 

Bernd said this is probably specified in https://github.com/berndbischl/ParamHelpers/blob/master/R/paramValueToString.R.

**Comment by jakob-r** [comment]
This would imply that we have to have some way to set options in ph. As this package is in maintenance mode from my point of view this feature will likely not be implemented. However, feel free to open a PR.

**Comment by pat-s** [comment]
Ok, no problem. Adding a `cat()` and using a fork does the job for me atm.

Will this option be available in `paradox`?

**Comment by jakob-r** [comment]
Logging is not done in ParamHelpers and as far as I can see also no truncation. Can you post this Issue in the package where it occurs, also including a minimal example?

**Comment by berndbischl** [comment]
Jakob you are wrong the problem is in ph

**Comment by berndbischl** [comment]
I posted the explanation in slack. The problem is parValueToString. That's not really logging but being able to convert a PH list of values to a reasonable string. And that calls clipString, with a hard wired clip.len...

**Comment by berndbischl** [comment]
And such a function seems so fundamental that it SHOULD really exist in PH and probably also in paradox...

**Comment by jakob-r** [comment]
If you want to, open this issue again with a proposal what should be done.

**Comment by berndbischl** [comment]
well, just quickly:
(and then maybe we can close again)

a) i completely agree that new development should be done in pd and not PH. so maybe the best thing is to do nothing here. also this is really not critical as in mlr you can write your own logger, and you have the OptPath with all the data.

b) Patrick is still right that this is bad what we did here (regarding a not so important thing..., see a)).
and it is a problem that really is in PH.

c) for me the relevant question is what do in pd? dont we want to have a "toString" method there? then we should at least make some notes so the same mistakes doesnt happen again

thats it

**Comment by berndbischl** [comment]
so my suggestion is to simply discuss and agree here, then open an issue in pd?

**Comment by jakob-r** [comment]
I opened this issue: https://github.com/mlr-org/paradox/issues/43

**Comment by berndbischl** [comment]
> I opened this issue: [mlr-org/paradox#43](https://github.com/mlr-org/paradox/issues/43)

thx
