### ISSUE TITLE
plotEAF

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/ParamHelpers#31]
The function under todofiles is nearly finished. We mainly need a nice example and some unit tests.

**Comment by danielhorn** [comment]
Finished the function and added unit test. A nice example is still missing. My idea would be to reuse our emo-results. Would that be okay? And - add the data to the package? Or calculate it in the example?

**Comment by berndbischl** [comment]
@danielhorn 
Can you try to finish this please.
I would rather create a very simply EAF data set with an optimizer that is on cran, eg mco, on a stupid test function. you can sure add the .DATA to the package. And the script to produce it

**Comment by jakob-r** [comment]
EAF has been implemented (and is now causing trouble)
