### ISSUE TITLE
plotOptPath

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/ParamHelpers#33]
We should have basic functions here to plot the OP.

Some stuff is already in mlrMBO, but is should be based here. It should also be shown in the mlr tutorial part on tuning.

**Comment by jakob-r** [comment]
Related: https://github.com/berndbischl/ParamHelpers/issues/34

**Comment by danielhorn** [comment]
Karin is working on this at the moment. We have basic functions to plot the X and Y-Space of every optPath. (Okay, not every optPath yet, but soon.) Wen can plot any dimensionality and every combination of discrete and numeric params, support for dependent params and missing values will be added this week.

Please look at the plots and report errors, feature requests, ...

At the moment we do have only functions for plotting a single optPath. Do we need plot functions for comparing 2 optPaths?

**Comment by berndbischl** [comment]
> Do we need plot functions for comparing 2 optPaths?

Hmm. Dealing with one is already good. The only thing I would like is to overlay MULTIPLE y-traces in one plot. That is very common?

**Comment by danielhorn** [comment]
This would be a special Plot for single-criterion optPaths? Or we could use the hypervolume for multicrit y-traces? And we could / should move the EAF-Plots to ParamHelpers.

**Comment by berndbischl** [comment]
I am talking about single crit now. In general this cases are separate I guess.

**Comment by berndbischl** [comment]
EAF: yes, probably

**Comment by berndbischl** [comment]
@danielhorn 
Any reason not to put this code on CRAN now?

**Comment by berndbischl** [comment]
plotYTraces and EAF allow comparisons.
The functionality is here, and is released in 1.6
