### ISSUE TITLE
Examples/tests fail when suggested packages not installed

### ISSUE THREAD

**Issue by hadley** [berndbischl/ParamHelpers#35]
```
checking examples ... ERROR
Running examples in ‘ParamHelpers-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: getOptPathParetoFront
> ### Title: Get indices of pareto front of optimization path.
> ### Aliases: getOptPathParetoFront
> 
> ### ** Examples
> 
> ps = makeParamSet(makeNumericParam("x"))
> op = makeOptPathDF(par.set = ps, y.names = c("y1", "y2"), minimize = c(TRUE, TRUE))
> addOptPathEl(op, x = list(x = 1), y = c(5, 3))
> addOptPathEl(op, x = list(x = 2), y = c(2, 4))
> addOptPathEl(op, x = list(x = 3), y = c(9, 4))
> addOptPathEl(op, x = list(x = 4), y = c(4, 9))
> as.data.frame(op)
  x y1 y2 dob eol
1 1  5  3   1  NA
2 2  2  4   2  NA
3 3  9  4   3  NA
4 4  4  9   4  NA
> getOptPathParetoFront(op)
Error in requirePackages("emoa", default.method = "load") : 
  Please install the following packages: emoa
Calls: getOptPathParetoFront -> requirePackages -> stopf
Execution halted
```
```
checking tests ... ERROR
Running the tests in ‘tests/run-all.R’ failed.
Last 13 lines of output:
         warning = function(c) invokeRestart("muffleWarning"))
  2: eval(code, new_test_environment)
  3: eval(expr, envir, enclos)
  4: requirePackages("_irace") at test_convertParamSetToIrace.R:4
  5: stopf("Please install the following packages: %s", ps)
  
  testthat results ================================================================
  OK: 759 SKIPPED: 0 FAILED: 2
  1. Error: pareto front 
  2. Error: convertParamSetToIrace 
  
  Error: testthat unit tests failed
  Execution halted
```

**Comment by berndbischl** [comment]
Hi. Under which setup do you notice that?
And yes for the full suite of tests we also require all SUGGESTS to be installed. Why is that a problem?

**Comment by hadley** [comment]
Because I have to check ~500 packages for the reverse dependencies on testthat, and not having to install all of the suggested packages saves a lot of time.  It's a bit murky, but R-exts suggests that R CMD check should pass even when you don't have suggested packages installed.

**Comment by berndbischl** [comment]
Well, but I would really like be clear here:

Is this an enforced CRAN policy? because if so I never knew.

**Comment by berndbischl** [comment]
I am also not against making your life easier, but mlr, where you also reported has like a million packages in SUGGESTS. I do not want to remove these tests. 

Can you please reference the proper way to write a testthat test for these "suggested" cases?

**Comment by hadley** [comment]
Use `skip_if_not_installed("package")` to skip tests that depend on a specific package. 

It's not a huge deal if you don't bother, but it false positives make it less likely that I'll recognise real problems when doing revdep checks.

**Comment by berndbischl** [comment]
Hadley, thanks for sharing this info. 
I will keep do this, and on general keep this is mind as the proper way.

But please wait a couple of days. I really need to do another CRAN updates, I have already kept those guys waiting for a bit too long and this has preference now. 

I will also discuss this with my co-developers so they know.

**Comment by berndbischl** [comment]
Hmm, do you know of a simple way if that problem STILL exists? I mean I have to go thru a million tests to add that line in the header. I will likely forget a few. How can I check against this?

**Comment by hadley** [comment]
I don't have an easy way to test :/  Conceptually what you should do is:

* Create an empty directory and set that as your `.libPath()`
* Install the dependencies of mlr (excluding suggests) into that library
* Run `R CMD check`

(BTW the plan is to release testthat in 2 weeks, and this isn't on the critical path anyway, so no rush)

**Comment by berndbischl** [comment]
Is it allowed to have a second travis target / setting? Where I would only install the dependencies and not the suggests? Then I guess I could see it automatically...

**Comment by larskotthoff** [comment]
@berndbischl I don't see a problem with having a second travis setup -- I think that would be a good idea anyway to have a job that finishes quickly.

**Comment by berndbischl** [comment]
@larskotthoff 
Could you set it up here for ParamHelpers? I could do all the details a la skip_if_not_installed

**Comment by larskotthoff** [comment]
@berndbischl Not sure how much sense that makes since the ParamHelpers installs only the direct dependencies anyway. What would you want to exclude in the "small" job?

**Comment by berndbischl** [comment]
Look at the trace above. We do not force the user to install eg emoa for multicriteria plots. 
This would be excluded in the new travis setup.

(For this package it would mainly be a test case with the 2 travis setups. we could handle it differently. much more important is mlr)

**Comment by larskotthoff** [comment]
I still don't know what you mean. This test would be skipped if the package is not installed -- and the current travis setup doesn't install it. That is, to see what `skip_if_not_installed` does we wouldn't need to change the travis setup.

**Comment by berndbischl** [comment]
We talked about this via hangout. Solutions might be

a) figure out we travis really allows multiple, different builds. we currently dont know
b) our own CI server
c) just to check this problem locally, maybe with some code in dt

I would really try to avoid b) as we would need to replicate rtravis nearly completely.

**Comment by mllg** [comment]
I don't get it. Why should this not work?

1. Add `skip_if_not_installed()` to respective unit tests.
2. Install suggested packages via `.travis.yml` by listing them in `r_packages` or `r_binary_packages`.

**Comment by berndbischl** [comment]
@mllg
First of all rtravis seems to always install the suggested packs. I checked the code yesterday for a few minutes, i am kinda sure.

second, how would you check whether you forgot one of these skip statements. i dont want hadley to open up more of these issues.

**Comment by berndbischl** [comment]
I really cannot fix this now, this is low prio. Complain if it hurts a lot
