### ISSUE TITLE
isFeasible should more work like expected

### ISSUE THREAD

**Issue by jakob-r** [berndbischl/ParamHelpers#40]
subset the ParamSet to what's necessary

**Comment by berndbischl** [comment]
This means: Only a subset of values of values for x in isFeasible(ps, x) should be allowed to pass.
See this here berndbischl/mlr#240

**Comment by jakob-r** [comment]
What is the suggested result of `isFeasible(ps, list())` ?
I will vote for `TRUE`.

**Comment by jakob-r** [comment]
I am working on it here: https://github.com/berndbischl/ParamHelpers/tree/fix_40_isFeasible

**Comment by berndbischl** [comment]
@jakob-r 
is this resolved with your current PR?

**Comment by jakob-r** [comment]
On merge of PR #73 this will be resolved
