### ISSUE TITLE
no defaults for `makeIntegerVectorLearnerParam` possible 

### ISSUE THREAD

**Issue by giuseppec** [berndbischl/ParamHelpers#47]
When the vector length is unkown, I can't set a default value for `makeIntegerVectorLearnerParam` when the default is a vector with length > 1.

This does not work:
```
makeNumericVectorLearnerParam("hidden", len = NA_integer_, default = c(10, 10))
```

This does works:
```
makeNumericVectorLearnerParam("hidden", len = NA_integer_, default = 10)
```

**Comment by berndbischl** [comment]
Should be fixed, pls check
