### ISSUE TITLE
Inf as default value not possible?

### ISSUE THREAD

**Issue by giuseppec** [berndbischl/ParamHelpers#48]
In `h2o.deeplearning` the default value for the `max_w2` parameter is `Inf`.
It is not possible to set this with ParamHelpers?

This does not work:
```
makeNumericLearnerParam("max_w2", default = Inf)
```

**Comment by berndbischl** [comment]
should be fixed now, pls check

**Comment by giuseppec** [comment]
Nope:

```{r}
p <- makeNumericLearnerParam("max_w2")
isFeasible(p, 1e100)
# [1] TRUE
isFeasible(p, 1e1000)
# [1] FALSE
isFeasible(p, Inf)
# [1] FALSE
```

**Comment by berndbischl** [comment]
you need to read the NEWS, use allow.inf :)

**Comment by berndbischl** [comment]
This HAS to be defined by the user, we cannot know apriori, whether infs are allowed values or not.
normally i would not allow them
