### ISSUE TITLE
generateDesign does not work with vector params and forbidden regions

### ISSUE THREAD

**Issue by danielhorn** [berndbischl/ParamHelpers#51]
Example:
```r
ps = makeParamSet(
  makeNumericVectorParam(id = "x", len = 2, lower = 0, upper = 1),
  forbidden = expression(sum(x) > 1)
)
max(rowSums(generateDesign(n = 100, par.set = ps)))
```

I think the problem is: In line 142 of generateDesign.R rowSapply(newres, isForbidden, par.set = par.set) is called. Here newres is a dataframe with the variables x1 and x2. And it converts these variables to a parameter-list list(x1 = bla, x2 = bla), but hasForbidden expects a parameter-list list(x = c(bla, bla)). So hasForbidden fails to find a variable x, since only x1 and x2 exist, and generateDesign ends with an error. Actually this code here works:
```r
ps = makeParamSet(
  makeNumericVectorParam(id = "x", len = 2, lower = 0, upper = 1),
  forbidden = expression(x1 + x2 > 1)
)
max(rowSums(generateDesign(n = 100, par.set = ps)))
```

**Comment by jakobbossek** [comment]
See PR #94
