### ISSUE TITLE
arg check "requires": must be a quote, not an expression

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/ParamHelpers#52]
requires can only be quoted, not an expression. 
we need an arg check here, and some tests.

**Comment by berndbischl** [comment]
there is code now in mlr, in these places.
checkParamSet
tuneParams
makeLearnerBaseConstructor

must be removed when this is closed

**Comment by berndbischl** [comment]
reason i am not doing this here now: will break mlr on cran

**Comment by mb706** [comment]
What is the beef with expressions? If quotes are required, maybe use something like
```R
convertExp2Quote = function(req) {
  if (is.expression(req)) {
    if (length(req) == 1) {
      return(req[[1]])
    } else {
      return(substitute(eval(x), list(x=req)))
    }
  }
  req
}
```
in the `makeXXXParam` constructors? It would keep the interface intact.

**Comment by berndbischl** [comment]
@jakob-r 
it would be great if we could resolve this now. best time to do this.

**Comment by berndbischl** [comment]
i like what @mb706 posted here. he is proposing to autoconvert this, so we have typesafety.
we should have to update docs then

**Comment by berndbischl** [comment]
I dont see how your PR #109 
solved this issue? please REALLY be careful with this especially when you auto-close.

**Comment by jakob-r** [comment]
Okay. So we want that autoconversion?

**Comment by larskotthoff** [comment]
This also broke mlr (fixed now).

**Comment by jakob-r** [comment]
Why is this open? Should be dealt with here:
https://github.com/berndbischl/ParamHelpers/commit/0e89bc2aa344e285b0fc444c7f8231223d54e46b

**Comment by berndbischl** [comment]
we also said the code must be removed in mlr. but that was also done long ago.

we are good here.
