### ISSUE TITLE
Adding infeasible discrete values to OptPath

### ISSUE THREAD

**Issue by jakobbossek** [berndbischl/ParamHelpers#58]
The following fails and it should not:
```splus
par.set = makeParamSet(
  makeDiscreteParam("disc", values = c("a", "b"))
)
opt.path = makeOptPathDF(par.set = par.set, y.names = "y", minimize = TRUE)
addOptPathEl(opt.path, x = list(disc = "c"), y = 1, check.feasible=FALSE)
```
> Fehler in getIndex(par$values, x) : Value not found!

**Comment by berndbischl** [comment]
ok i see. thx.

**Comment by berndbischl** [comment]
there is a certain semantic problem though. we cannot allow ANY type of value to be added to the optpath.

I mean, what happens if the the column i numeric, and you add a string? certainly you dont want me to allow that too?

**Comment by berndbischl** [comment]
actually, now that I am remembering it, check.feasible = FALSE, was mainly meant as a "time saver".
so if you are REALLY sure that the value you add is OK, you can save some time by disabling the check.

It was never really meant to allow you to add an infeasible value to the path.... which is what you are trying to force here.

**Comment by jakobbossek** [comment]
Yeah, I think we allow only infeasible integer values integer params? Why not allow to add arbitrary string values for discrete params. I mean, if you set `check.feasible` to `false`, you certainly know what you do.

**Comment by berndbischl** [comment]
well it is kinda a documentation issue. actually you SHOULD ONLY add feasible values.

If you set check.feasible = FALSE that is still true. it merely means, that i dont do a proper "arg check" for you, to produce a good error message, so you save some time. 

that you CAN actually add infeasible values was never really meant as a "feature". the feature was to save the time for the formal arg check.

i can work on this, but the problem is we need SOME constraints. if I allow eg arbitrary values for discrete i could never store values as "factor", but only "char". do we want that? will slow down stuff even more.

**Comment by jakobbossek** [comment]
Ok, good point.
My idea was to store arbitrary genotypes in ecr as serialized objects as a discrete dummy parameter.

**Comment by berndbischl** [comment]
explain it better. how do the params look like? arbitrary strings?

**Comment by jakobbossek** [comment]
Yes, imagine your EA works, e.g., on the following non-standard representation
```splus
individual = list(x = matrix(...), y = "string", z = list(...))
```
Because I would like to use the opt path without a load of neccessary adaptions for such custom representations I would generate a *dummy* parameter set
```splus
par.set = makeParamSet(
  makeDiscreteParam("x", values = "dummy")
)
opt.path = makeOptPathDF(par.set = par.set, minimize = TRUE, y.names = "y")
```
and store the individual as follows:
```splus
serialized = rawToChar(serialize(individual, connection = NULL, ascii = TRUE))
addOptPathEl(opt.path, x = list(x = serialized), y = 1.4, check.feasible = FALSE)
```
Not the most elegant way, but it would be helpful for the moment.
Maybe better introduce a `StringParam` type?

**Comment by berndbischl** [comment]
stringparam could be added. we also have "untyped" (which probably does not work for the optopath)
i guess string is best here, right?

**Comment by jakobbossek** [comment]
Yes, I think adding stringParam is the best option. I will assign myself.

**Comment by berndbischl** [comment]
cool. thx

**Comment by jakobbossek** [comment]
Going to call that stuff CharacterParam. This is more consistent with the R naming.

**Comment by berndbischl** [comment]
Not that we ever chose good names for things in this package

**Comment by jakobbossek** [comment]
:smile: At least the params are consistent with the R data types.

**Comment by jakobbossek** [comment]
Added a basic CharacterParam. No necessary construction parameters beside the id. Maybe we could introduce some regexp expression to check values against, but at the moment this is not necessary I guess. Sufficient for my needs. Take a look at it and close if you have nothing to complain.

**Comment by berndbischl** [comment]
thx. i will review it later. but in te future pls only do pull requests here. everybody does those for mlr, including me.

**Comment by berndbischl** [comment]
ok i already looked at. can you please add more tests? the package offers a lot more operations.

and some comments already:
- gen*Design will not work right? and should produce a meaningful error?
- shouldnt there also be a Learner param then?

we also need to haste here a bit as need to upload PH very quickly. thats also why a PR would have been better.

**Comment by jakobbossek** [comment]
Ok, going to add more tests, a learner param and a character vector param not later than monday.

**Comment by jakobbossek** [comment]
Did not know about the pull requests procedure. Going to keep it in mind for the future.

**Comment by jakobbossek** [comment]
I am not sure whether I understand the sense of `cnames`. I think it is not relevant for CharacterVectorParams, is it?

**Comment by jakobbossek** [comment]
Do we really need a `CharacterLearnerParam`? What would be the use case for that? In general string parameters for learners are restricted to a discrete set and hence a `discrete{Vector}?Param` is the better choice.

**Comment by jakobbossek** [comment]
Added `CharacterVectorParam`, `{is,has}Character` helpers and extended a lot of tests.

**Comment by berndbischl** [comment]
> Did not know about the pull requests procedure. Going to keep it in mind for the future.

Read here, we tried to define our workflow here. 
https://github.com/mlr-org/mlr/wiki/mlr-Coding-Guidelines

IMHO pull requests are even better for the core developers, as code becomes much better through buddy review

> Do we really need a CharacterLearnerParam? 

Maybe not. You can leave it out for now. I could imagine this, but I cannot come up with a good example.

**Comment by jakobbossek** [comment]
Ok, thanks for the link. Is on my toRead list now.
Please review and tell me if I can close this issue.

**Comment by berndbischl** [comment]
> I am not sure whether I understand the sense of cnames. 
> I think it is not relevant for CharacterVectorParams, is it?

Where exactly do you mean? cnames or *C*omponentnames of a value. So if you implement now a CharacterVectorParam, I guess it is relevant.

**Comment by mllg** [comment]
I've allowed passing of `cnames` and did some cleanups in 34aa3d39a1eef6ec44100df496c5c3bb6a968fde. Should be fine now.
