### ISSUE TITLE
What is numeric?

### ISSUE THREAD

**Issue by jakob-r** [berndbischl/ParamHelpers#60]
How does that make any sense?

```r
> ps = makeParamSet(
+ makeIntegerParam("y", lower = 2, upper= 6)
+ )
> hasNumeric(ps)
[1] TRUE
> sapply(ps$pars, isNumeric)
   y 
TRUE 
> filterParams(ps, type = "numeric")
[1] "Empty parameter set."
```

*it doesn't*

**Comment by berndbischl** [comment]
RTFM?

**Comment by berndbischl** [comment]
i mean it is pretty clear what happens?
hasNumeric has "include.int"

**Comment by berndbischl** [comment]
we can now discuss whether filterParams should have that, too. Or what the default should be.
But the piunt is, it is well documented what currently happens, and if you set include.int=F, both functions do the same thing.

**Comment by berndbischl** [comment]
or you need to add the "int" type to filterParams. And dont forget vectors either

**Comment by jakob-r** [comment]
See my PR #59 I added a little helper.
But yeah with vectors it gets more confusing
```r
> ps = makeParamSet(
+ makeNumericVectorParam("yv", len = 2)
+ )
> hasNumeric(ps)
[1] TRUE
> sapply(ps$pars, isNumeric)
  yv 
TRUE 
> filterParams(ps, type = "numeric")
[1] "Empty parameter set."
```
And of course you can read the manual but still there is some inconsistency in the naming, don't you agree?

**Comment by berndbischl** [comment]
No, its not that confusing as filterParams clearly states the types you can filter for? 
I mean, what happens if you call makeNumericParam?
You create a scalar. 

If you want this to move on, pls make a clear suggestion what is exactly inconsistent or wrong.
And preferably how to change it.

**Comment by berndbischl** [comment]
You can also suggest a doc fix.

**Comment by jakob-r** [comment]
Then let's leave it like that.
