### ISSUE TITLE
..mlr::filterFeature is broke with ParamHelpers 1.7..

### ISSUE THREAD

**Issue by lenz99-** [berndbischl/ParamHelpers#68]
Hallo there.

I report an error in `mlr:::filterFeature` when I have updated to ParamHelpers 1.7

Here is an example:

```
library(mlr)

task = makeClassifTask(data = iris, target = "Species")
filterFeatures(task, perc = .85)

```
Which gives me:
```
Fehler in filterFeatures(task, perc = 0.85) : 
  Assertion on 'sapply(method, function(x) assertChoice(x, choices = ls(.FilterRegister)))' failed. NA
Zusätzlich: Warnmeldung:
In all(sapply(method, function(x) assertChoice(x, choices = ls(.FilterRegister)))) :
  wandle Argument des Typs 'character' nach boolesch

```
I am using here R 3.2.3 and mlr 2.7 and the newly released ParamHelpers 1.7

It works fine under ParamHelper 1.6 so I guess the problem has been introduced in 1.7 somewhere.

-m

**Comment by berndbischl** [comment]
Hi Max,

thx will look at this at once and update to 1.7.1.

Can you please tell me how you stumpled upon this? In code of one of your packages or custom code?

**Comment by berndbischl** [comment]
Hmm. The whole thing is strange as the unit tests DO run, as I also checked before uploading PH. And the above call is very simple and basic. Ok, I will trace this then

**Comment by lenz99-** [comment]
Hallo Bernd.

It came up in my own package where I evaluate different learners which are fused with feature filtering (`makeFilterWrapper`).
Strangely, the error remains when I downgrade to PH 1.6
I will try to do a fresh library-directory for R on this machine (it's linux) 
thanks for looking into this.
-m

**Comment by berndbischl** [comment]
I guess this is more a problem in mlr code. I can only reproduce the error, if I use mlr 2.7 from CRAN.
With mlr 2.8, from GH, the code runs. 

And I am right now in the process of releasing.

Could you check with the GH version please and tell me if all of your stuff works?

**Comment by lenz99-** [comment]
Yes, the Github version does __not__ throw the error. -m

**Comment by lenz99-** [comment]
Oh, already closed the issue. I just wanted to comment.. sorry. but maybe this is already the fix?! -m

**Comment by berndbischl** [comment]
Thx + I would have closed anyhow in this case. 
I will now prepare the release.

Just remember to depend on 2.8 on your side then
