### ISSUE TITLE
What was the intention of `makeFunctionParam`?

### ISSUE THREAD

**Issue by tijoseymathew** [berndbischl/ParamHelpers#70]
From what I gather going over the codes, `makeFunctionParam` and `makeLearnerFunctionParam` creates a `param` with a `default` value? What is this `default` value?
How can we pass a `function` to this function?

I am interested in trying to extend `makeFunctionParam` to task-dependent parameters. Basically, a `param` of type function will store a function that takes a task as argument and returns one of the more basic `param`. This can then be further used to tune the learner.

**Comment by berndbischl** [comment]
Well, the intention was simply to be able to describe a param which is an R function. 
I have to admit you cannot do that much with that info. Well, args checks, and the user has some meta info now about the object. 





> I am interested in trying to extend makeFunctionParam to task-dependent parameters. Basically, a param of type function will store a function that takes a task as argument and returns one of the more basic param. This can then be further used to tune the learner.

Do you want to talk about this? We are already working on possibly the same thing.

**Comment by tijoseymathew** [comment]
Yeah sure. I really need task-dependent tuning of parameters to work so that I can use `mlr`. I will be happy to help out.

**Comment by berndbischl** [comment]
Ok, do you want to drop me an email?
We can then schedule a hangout meeting. Would be cool if you could briefly describe your project / goal.
bernd_bischl@gmx.net

**Comment by tijoseymathew** [comment]
Just checking in if you got my email?

**Comment by berndbischl** [comment]
just replied

**Comment by berndbischl** [comment]
I will close this here, as the question itself is answered. we can discuss in a more precise thread
