### ISSUE TITLE
debug info for why isFeasible is FALSE

### ISSUE THREAD

**Issue by mb706** [berndbischl/ParamHelpers#80]
Sometimes I find myself in a position where a parameter fails `isFeasible` and I don't immediately know why. A "verbose" flag that gives some info about the reason a point is infeasible would be helpful here.

**Comment by jakob-r** [comment]
This is already adressed in PR #73. I am still waiting for a merge form @berndbischl.
If something should be missing then, feel free to contact us.

**Comment by mb706** [comment]
Ah, hadn't seen that, great!
