### ISSUE TITLE
addOptPathEl without extras to optPath with extras causes trouble

### ISSUE THREAD

**Issue by jakob-r** [berndbischl/ParamHelpers#90]
```r
ps = makeParamSet(makeNumericParam("v"))
op = makeOptPathDF(par.set = ps, y.names = "y", minimize = TRUE, include.extra = TRUE)
addOptPathEl(op, x = list(v = 1), y = 5, extra = list(ee = 7))
addOptPathEl(op, x = list(v = 2), y = 6)
as.data.frame(op)
#Error in as.data.frame(op) : 
#  Assertion on 'rows' failed: May only contain the following types: vector
```
Maybe we want an Error if we try to add an element without extras or we determine some empty default.

**Comment by jakobbossek** [comment]
Agree.
I think we should force the user to pass extras if he decided to and not introduce any defaults.
How would you set a default value, e.g., if the first added element has no associated extras?

**Comment by jakobbossek** [comment]
We could simply set the default to `NA` and handle this case in all the helper functions like `convertListOfRowsToDataFrame` which is used to transform the extras list inside the `OptPath` into a `data.frame`. However, I think this is not worth the effort.

**Comment by jakobbossek** [comment]
Issue #19 seems to be linked.

**Comment by berndbischl** [comment]
I dont like this so much. Shouldnt we rather use rbind.fill when we convert the OP to a df?
then one can more flexibly add "extras" to specific rows?

**Comment by jakob-r** [comment]
@berndbischl and @jakob-r decided that we will use rbindList(fill = TRUE)

**Comment by berndbischl** [comment]
ok, we did not use rbind.fill.

first of all, the underlying code calls BBmisc::convertListOfRowsToDataFrame.
and this would need to be changed to enable an rbind.fill like behavior.

second, we already had check in PH to ensure that if a new extra is added, this has the same structure as the stuff in the extra list which had been added before. the only problem here was that this check did not work if we added a NULL in extra sometime later. 

so we disallowed this. if extras are enabled, you need to add them all the time. and they have to be structurally equivalent to what was added before.

**Comment by jakob-r** [comment]
Except you use the dotted extras? (question)

**Comment by berndbischl** [comment]
> Except you use the dotted extras? (question)

i cannot parse the question?

do you mean what i explained only holds for the nondots? so 
"what you said holds: Except *if* you use the dotted extras? (question)"

?

then i think the answer is "yes". 

i am not sure if this is a problem?
do we  need a further check here?

**Comment by jakob-r** [comment]
No further check needed. Will use dotted extras to put random stuff in OptPath, will write if problem occurs.

**Comment by berndbischl** [comment]
cool thx

**Comment by berndbischl** [comment]
also: we then have a nice "flexible" alternative :)
